### ISSUE TITLE
Stuck In "Lurk Mode"

### ISSUE THREAD

**Issue by Lithium876** [heyjordn/lurk#3]
If for any reason I want to go back to the default twitter view I have to remove the add-on. This might be a hassle especially if I only want the default view for a couple seconds, I'd have to remove the extension and restart the browser to get back the default view, then re install the add-on and restart the twitter tab when I want to go back in "lurk mode". I suggest making you add a toggle feature on to the addon so users can easily toggle "lurk mode" on and off at will. It would be nice if you get even get that in shortcuts as well.

**Comment by heyjordn** [comment]
The extension can be disabled/enabled from the chrome settings panel, takes effect once the page is reloaded. See gif below
![](https://raw.githubusercontent.com/Pr0x1m4/lurk/master/screenshots/lurk.gif)
